#!/bin/bash
#this works with moc and is in the moc config

file=$(echo "$4" | sed "s/\.flac$\|\.mp3$\|\.aac$\|\.m4a$\|\.ape$\|\.ogg$//")

if   [ "$1" = "gl" ]; then
  if [ -f "$file" ]; then
    notify-send "lyrics exist!"
  else
      glyrc lyrics -t "$2" -a "$3" -w "$file"
  fi
elif [ "$1" = "copy" ] && [ -f "$file" ]; then
       xsel -b < "$file"
elif [ "$1" = "show" ] && [ -f "$file" ]; then
      bat --paging=always --style=header,grid "$file"
elif [ "$1" = "cly" ]; then
      clyrics -m | tee "$file"
else
      exit 1
fi
