#!/bin/bash
#this works with moc and is in the moc config

choice="$1"
track="$2"
artist="$3"
filepath="$4"

file=$(echo "$filepath" | sed "s/\.flac$\|\.mp3$\|\.aac$\|\.m4a$\|\.ape$\|\.ogg$\|\.opus$//")

if   [ "$choice" = "gl" ]; then
  if [ -f "$file" ]; then
    notify-send "lyrics exist!"
  else
      if mediainfo "$filepath" | grep -q "Lyrics"; then
          mediainfo "$filepath" | awk -F: "/Lyrics/ {print \$2}" | sed 's#/#\n#g' > "$file" &&
              notify-send "$track Lyrics using `mediainfo` created" || notify-send "could not use `mediainfo` for $track" &
      else
          notify-send "Started downloading the $track lyrics!" &&
              proxychains glyrc lyrics -t "$track" -a "$artist" -w "$file" > /dev/null 2>&1 &&
              notify-send "$track Lyrics Downladed!" || notify-send "Could not download the lyrics for " "$track" &
      fi
  fi
elif [ "$choice" = "copy" ]; then
  if [ -f "$file" ]; then
      xsel -b < "$file"
  else
      notify-send "Lyrics Doesn't exist!"
  fi
elif [ "$choice" = "show" ]; then
  if [ -f "$file" ]; then
   # bat --paging=always --style=header,grid "$file"
      less -i "$file"
  else
      notify-send "Lyrics Doesn't exist!"
  fi
elif [ "$choice" = "cly" ]; then
      clyrics "$artist" "$track" | tee "$file"
else
      exit 1
fi
